apiVersion: batch/v1
kind: CronJob
metadata:
  name: artic-illumina-inputdata-cronjob
spec:
  schedule: "* 0 * * *"
  jobTemplate:
    metadata:
      labels:
        ms: artic-illumina-inputdata-cronjob
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: ctr26/artic-illumina-inputdata-cronjob
          env:
            - name: DATA_HUB
              valueFrom:
                configMapKeyRef:
                  name: artic-inputdata-config
                  key: data-hub
            - name: DATA_HUB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: artic-inputdata-config
                  key: data-hub-password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: wms
              mountPath: /wms
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: artic-illumina-data-pvc
        - name: wms
          persistentVolumeClaim:
            claimName: ena-wms-pvc
