apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: vcf-pipeline-run-job
    spec:
      restartPolicy: Never
      nodeSelector:
        analysis: vcf
      containers:
      - image: alexeyebi/vcf-pipeline-run-job
        name: vcf-pipeline-run-job
        args: ["ERR4164785"]
        volumeMounts:
          - name: data
            mountPath: /data
          - name: output
            mountPath: /output
          - name: sourcecode
            mountPath: /git
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jovian-inputdata-pvc
        - name: sourcecode
          persistentVolumeClaim:
            claimName: vcf-sourcecode-pvc
        - name: output
          persistentVolumeClaim:
            claimName: vcf-pipeline-pvc
