apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-pipeline-run-job
spec:
  parallelism: 50
  template:
    metadata:
      labels:
        ms: vcf-pipeline-run-job
    spec:
      restartPolicy: Never
      nodeSelector:
        vcf: primary
      imagePullSecrets:
        - name: ebi-registry-secret
      containers:
      - image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/vcf-pipeline-run-job
        name: vcf-pipeline-run-job
        volumeMounts:
          - name: data
            mountPath: /data
          - name: output
            mountPath: /output
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
