apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: vcf-pipeline-run-job
      annotations:
        scheduling.k8s.io/group-name: vcf-podgroup
    spec:
      restartPolicy: Never
      schedulerName: kube-batch
      containers:
      - image: alexeyebi/vcf-pipeline-run-job
        name: vcf-pipeline-run-job
        args: ["ERR4164785"]
        volumeMounts:
          - name: data
            mountPath: /data
          - name: sourcecode
            mountPath: /git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sars-cov2-sequence-analysis-pvc
        - name: sourcecode
          persistentVolumeClaim:
            claimName: vcf-sourcecode-pvc
