apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-pipeline-run-job
spec:
  parallelism: 50
  template:
    metadata:
      labels:
        ms: vcf-pipeline-run-job
    spec:
      restartPolicy: Never
      nodeSelector:
        vcf: primary
      containers:
      - image: rmwthorne/vcf-pipeline-run-job
        name: vcf-pipeline-run-job
        volumeMounts:
          - name: data
            mountPath: /data
          - name: output
            mountPath: /output
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jovian-inputdata-pvc
        - name: output
          persistentVolumeClaim:
            claimName: vcf-pipeline-pvc
