apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-pipeline-run-job
spec:
  parallelism: 20
  template:
    metadata:
      labels:
        ms: vcf-pipeline-run-job
    spec:
      restartPolicy: Never
      containers:
      - image: alexeyebi/vcf-pipeline-run-job
        name: vcf-pipeline-run-job
        volumeMounts:
          - name: data
            mountPath: /data
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
