apiVersion: batch/v1
kind: Job
metadata:
  name: artic-illumina-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: artic-illumina-pipeline-run-job
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - ebi-registry-secret
      containers:
        - name: artic-illumina-pipeline-run-pod
          image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/artic-pipeline-run-job
          args: ["ERR4164785", "illumina"]
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: artic-pipeline-config
                  key: user
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: artic-pipeline-config
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: sourcecode
              mountPath: /git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: artic-illumina-data-pvc
        - name: sourcecode
          persistentVolumeClaim:
            claimName: artic-sourcecode-pvc
