variables:
  DOCKER_TLS_CERTDIR: ''

stages:
  - deploy

services:
  - docker:19.03.0-dind

deploy_images:
  stage: deploy
  image: docker/compose:1.28.6
  script:
    - >
      if [ "$CI_BUILD_REF_NAME" == "master" ]
        then export TAG=latest
        else export TAG=$CI_BUILD_REF_NAME
      fi
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - master
    - staging
