apiVersion: v1
data:
  git-sync-branch: master
  git-sync-dest: /git
  git-sync-repo: https://github.com/enasequence/covid-workflow-manager.git
  git-sync-rev: FETCH_HEAD
  git-sync-wait: "10"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ena-wms-config
  selfLink: /api/v1/namespaces/ross-covid-19/configmaps/ena-wms-config
