apiVersion: v1
kind: Service
metadata:
  name: auspice-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    ms: auspice

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auspice-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        ms: auspice
    spec:
      containers:
      - name: auspice
        image: staphb/auspice
        command: ["auspice", "view"]
        ports:
        - containerPort: 5000

