apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    ms: mongo-express

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployments
spec:
  selector:
    matchLabels:
      ms: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        ms: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: alexeyebi/mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "true"
          - name: ME_CONFIG_BASICAUTH_USERNAME
            value: "covid-19-analyses-public"
          - name: ME_CONFIG_BASICAUTH_PASSWORD
            value: "T}9[r72h"
          - name: ME_CONFIG_OPTIONS_READONLY
            value: "true"
          - name: ME_CONFIG_OPTIONS_NO_DELETE
            value: "true"