apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-api-job-hello-world
spec:
  template:
    spec:
      containers:
      - name: k8s-api-job-hello-world
        image: hello-world
        # command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4