apiVersion: batch/v1
kind: Job
metadata:
  name: pangolin-annotate-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: rmwthorne/m-pangolin
          command: [
            "python",
            "./annotate.py",
            "/consensus/",
            "-g", "*.fa",
            "--tempdir", "/pangolin/tmp/",
            "-t", "16",
            "-o", "/pangolin/"
          ]
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /pangolin
            - name: consensus
              mountPath: /consensus
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pangolin-pvc
        - name: consensus
          persistentVolumeClaim:
            claimName: consensus-pvc

