apiVersion: batch/v1
kind: Job
metadata:
  name: jovian-databases-job
spec:
  template:
    metadata:
      labels:
        ms: jovian-databases-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: alexeyebi/jovian-databases-job
        volumeMounts:
          - name: data
            mountPath: /database
          - name: code
            mountPath: /git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
        - name: code
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
