apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pangolin-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    metadata:
      labels:
        ms: pangolin-cronjob
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: rmwthorne/pangolin-cronjob
              env:
                - name: SOURCE
                  value: rest # 'rest' or 'ftp'
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: pangolin-pvc

