apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pangolin-cronjob
spec:
  schedule: "00 10 * * *" # 10:00am daily
  jobTemplate:
    metadata:
      labels:
        ms: pangolin-cronjob
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: rmwthorne/pangolin-cronjob
              env:
                - name: SOURCE
                  value: rest
                - name: PYTHONUNBUFFERED
                  value: "1"
                - name: DEBUG
                  value: "False"
              volumeMounts:
                - name: data
                  mountPath: /data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: pangolin-pvc

