apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: consensus-inputdata-cronjob
spec:
  schedule: "0 10 * * *" # 10:00am daily
  jobTemplate:
    metadata:
      labels:
        ms: consensus-inputdata-cronjob
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: rmwthorne/consensus-inputdata
              command: ["python3", "get_fasta.py", "-o", "/consensus/"]
              resources:
                requests:
                  cpu: "1"
                  memory: "512Mi"
                limits:
                  cpu: "4"
                  memory: "10Gi"
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              volumeMounts:
                - name: consensus
                  mountPath: /consensus
          volumes:
            - name: consensus
              persistentVolumeClaim:
                claimName: consensus-pvc

