kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jovian-inputdata-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: nfs-client
