apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jovian-inputdata-pvc
spec:
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jovian-inputdata-cronjob
spec:
  schedule: "@weekly"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: rmwthorne/jovian-inputdata-cronjob
            name: jovian-inputdata-job
            env:
              - name: DATA_HUB
                valueFrom:
                  configMapKeyRef:
                    name: jovian-inputdata-config-greece
                    key: data-hub
              - name: DATA_HUB_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: jovian-inputdata-config-greece
                    key: data-hub-password
            volumeMounts:
              - name: data
                mountPath: /raw_data
              - name: wms
                mountPath: /wms
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: jovian-inputdata-pvc
            - name: wms
              persistentVolumeClaim:
                claimName: ena-wms-pvc
