apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    ms: mongodb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: example-nfs
  accessModes:
  - ReadWriteMany

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployments
spec:
  selector:
    matchLabels:
      ms: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        ms: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-pvc