apiVersion: batch/v1
kind: Job
metadata:
  name: ont-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: ont-pipeline-run-job
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ebi-registry-secret
      containers:
        - image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/ont-pipeline-run-job
          name: ont-pipeline-run-pod
          args: ["ERR4164785"]
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: ont-pipeline-config
                  key: user
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: ont-pipeline-config
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: sourcecode
              mountPath: /git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ont-data-pvc
        - name: sourcecode
          persistentVolumeClaim:
            claimName: ont-sourcecode-pvc
