apiVersion: batch/v1
kind: CronJob
metadata:
  name: artic-ont-inputdata-cronjob
spec:
  schedule: "* 0 * * *"
  jobTemplate:
    metadata:
      labels:
        ms: artic-ont-inputdata-cronjob
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/artic-ont-inputdata-cronjob
          env:
            - name: DATA_HUB
              valueFrom:
                configMapKeyRef:
                  name: artic-inputdata-config
                  key: data-hub
            - name: DATA_HUB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: artic-inputdata-config
                  key: data-hub-password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: wms
              mountPath: /wms
      imagePullSecrets:
        - name: ebi-registry-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: artic-ont-data-pvc
        - name: wms
          persistentVolumeClaim:
            claimName: ena-wms-pvc
