apiVersion: batch/v1
kind: Job
metadata:
  name: artic-ont-inputdata-cronjob
spec:
  # schedule: "* 0 * * *"
  template:
    metadata:
      labels:
        ms: artic-ont-inputdata-cronjob
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: ctr26/artic-ont-inputdata-cronjob
          env:
            - name: DATA_HUB
              valueFrom:
                configMapKeyRef:
                  name: artic-inputdata-config
                  key: data-hub
            - name: DATA_HUB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: artic-inputdata-config
                  key: data-hub-password
          volumeMounts:
            - name: data
              mountPath: /data
            - name: wms
              mountPath: /wms
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: artic-ont-data-pvc
        - name: wms
          persistentVolumeClaim:
            claimName: ena-wms-pvc
