apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artic-ont-data-pvc
spec:
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
