apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: metadata-cronjob
spec:
  schedule: "30 10 * * *" # 10:30 daily
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            ms: metadata-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: rmwthorne/metadata-inputdata
              command: ["python3", "get_seq_metadata.py", "-o", "/metadata/metadata.tsv"]
              resources:
                requests:
                  cpu: "1"
                  memory: "512Mi"
                limits:
                  cpu: "4"
                  memory: "10Gi"
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              volumeMounts:
                - name: metadata-pvc
                  mountPath: /metadata
          volumes:
            - name: metadata-pvc
              persistentVolumeClaim:
                claimName: metadata-pvc

