apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sars-cov2-sequence-analysis-pvc
spec:
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
