apiVersion: batch/v1
kind: Job
metadata:
  name: vcf-inputdata-cronjob
spec:
  template:
    metadata:
      labels:
        ms: vcf-inputdata-cronjob
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ebi-registry-secret
      containers:
        - name: main
          image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/vcf-inputdata-cronjob
          volumeMounts:
            - name: data
              mountPath: /data
            - name: wms
              mountPath: /wms
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sars-cov2-sequence-analysis-pvc
        - name: wms
          persistentVolumeClaim:
            claimName: ena-wms-pvc
