apiVersion: v1
kind: Service
metadata:
  name: kooplex-proxy-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    ms: proxy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kooplex-proxy-deployments
spec:
  selector:
    matchLabels:
      ms: proxy
  replicas: 1
  template:
    metadata:
      labels:
        ms: proxy
    spec:
      containers:
      - name: proxy
        image: alexeyebi/kooplex-proxy
        ports:
          - containerPort: 8080
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-admin-ebi
                key: admin
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-admin-ebi
                key: adminpw
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: pg-admin-ebi
                key: dbhost
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pg-admin-ebi
                key: db