apiVersion: batch/v1
kind: Job
metadata:
  name: jovian-pipeline-installation-job
spec:
  template:
    metadata:
      labels:
        ms: jovian-pipeline-installation-job
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ebi-registry-secret
      containers:
      - name: main
        image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/jovian-pipeline-installation-job
        volumeMounts:
          - name: sourcecode
            mountPath: /git
          - name: databases
            mountPath: /mnt/database
      volumes:
        - name: sourcecode
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
        - name: databases
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
