apiVersion: batch/v1
kind: Job
metadata:
  name: jovian-pipeline-installation-job
spec:
  template:
    metadata:
      labels:
        ms: jovian-pipeline-installation-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: rmwthorne/jovian-pipeline-installation-job
          volumeMounts:
            - name: sourcecode
              mountPath: /git
            - name: databases
              mountPath: /databases
      volumes:
        - name: sourcecode
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
        - name: databases
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
