__default__:
  threads: 1
  vmem: 4G
  nodes: 1
  time: 00:30:00

QC_raw_data:
  threads: 1
  vmem: 8G

Clean_the_data:
  threads: 4
  vmem: 16G
  time: 04:00:00

QC_clean_data:
  threads: 1
  vmem: 8G

HuGo_removal_pt1_alignment:
  threads: 4
  vmem: 4G
  time: 12:00:00

HuGo_removal_pt2_extract_paired_unmapped_reads:
  threads: 4
  vmem: 2G
  time: 02:00:00

HuGo_removal_pt3_extract_unpaired_unmapped_reads:
  threads: 4
  vmem: 2G
  time: 02:00:00

De_novo_assembly:
  threads: 12
  vmem: 10G
  time: 24:00:00

Fragment_length_analysis:
  threads: 4
  vmem: 8G
  time: 04:00:00

SNP_calling:
  threads: 12
  vmem: 6G
  time: 04:00:00

ORF_analysis:
  threads: 1
  vmem: 16G
  time: 04:00:00

Generate_contigs_metrics:
  threads: 1
  vmem: 64G
  time: 04:00:00

Determine_GC_content:
  threads: 1
  vmem: 24G
  time: 04:00:00

Generate_IGVjs_html_file:
  threads: 1
  vmem: 2G
  time: 02:00:00

MultiQC_report:
  threads: 1
  vmem: 4G
  time: 01:00:00

Scaffold_classification:
  threads: 12
  vmem: 8G
  time: 08:00:00

Krona_chart_combine:
  threads: 1
  vmem: 32G
  time: 04:00:00

quantify_output:
  threads: 4
  vmem: 4G
  time: 02:00:00

draw_heatmaps:
  threads: 1
  vmem: 4G
  time: 02:00:00

Merge_all_metrics_into_single_tsv:
  threads: 1
  vmem: 8G
  time: 02:00:00

Concat_files:
  threads: 1
  vmem: 2G
  time: 02:00:00

Generate_index_html:
  threads: 1
  vmem: 256M
  time: 00:15:00

Concat_filtered_SNPs:
  threads: 1
  vmem: 4G
  time: 02:00:00
