kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jovian-outputdata-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
