apiVersion: batch/v1
kind: Job
metadata:
  name: jovian-pipeline-run-job
spec:
  template:
    metadata:
      labels:
        ms: jovian-pipeline-run-job
    spec:
      restartPolicy: Never
      priorityClassName: high-priority-nonpreempting
      nodeSelector:
        analysis: jovian
      containers:
      - name: main
        image: alexeyebi/jovian-pipeline-reference-alignment-run-job
        args: ["jovian-pipeline-reference-alignment-run-job"]
        resources:
          limits:
            cpu: "15"
            memory: "50Gi"
          requests:
            cpu: "15"
            memory: "50Gi"
        volumeMounts:
          - name: sourcecode
            mountPath: /git
          - name: databases
            mountPath: /databases
          - name: data
            mountPath: /raw_data
          - name: results
            mountPath: /output
          - name: wms
            mountPath: /wms
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: sourcecode
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
        - name: databases
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
        - name: data
          persistentVolumeClaim:
            claimName: jovian-inputdata-pvc
        - name: results
          persistentVolumeClaim:
            claimName: jovian-outputdata-pvc
        - name: wms
          persistentVolumeClaim:
            claimName: ena-wms-pvc
