apiVersion: batch/v1
kind: CronJob
metadata:
  name: jovian-databases-cronjob
spec:
  schedule: "* * * * 0"
  jobTemplate:
    metadata:
      labels:
        ms: jovian-databases-cronjob
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ebi-registry-secret
      containers:
      - name: main
        image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/jovian-databases-cronjob
        volumeMounts:
          - name: data
            mountPath: /mnt/database
          - name: code
            mountPath: /git
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jovian-databases-pvc
        - name: code
          persistentVolumeClaim:
            claimName: jovian-sourcecode-pvc
