apiVersion: apps/v1
kind: Deployment
metadata:
  name: artic-sourcecode-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      ms: artic-sourcecode
  template:
    metadata:
      labels:
        ms: artic-sourcecode
    spec:
      containers:
      - image: openweb/git-sync
        name: artic-sourcecode
        env:
        - name: GIT_SYNC_REPO
          valueFrom:
            configMapKeyRef:
              name: artic-sourcecode-config
              key: git-sync-repo
        - name: GIT_SYNC_DEST
          valueFrom:
            configMapKeyRef:
              name: artic-sourcecode-config
              key: git-sync-dest    
        - name: GIT_SYNC_BRANCH
          valueFrom:
            configMapKeyRef:
              name: artic-sourcecode-config
              key: git-sync-branch
        - name: GIT_SYNC_REV
          valueFrom:
            configMapKeyRef:
              name: artic-sourcecode-config
              key: git-sync-rev
        - name: GIT_SYNC_WAIT
          valueFrom:
            configMapKeyRef:
              name: artic-sourcecode-config
              key: git-sync-wait
        volumeMounts:
          - name: git
            mountPath: /git
          - name: wms
            mountPath: /wms
          - name: data
            mountPath: /data
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: artic-sourcecode-pvc
        - name: wms
          persistentVolumeClaim:
            claimName: ena-wms-pvc
        - name: data
          persistentVolumeClaim:
            claimName: artic-ont-data-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artic-sourcecode-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
