apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: phylogeny-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            ms: phylogeny-cronjob
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: rmwthorne/phylogeny-cronjob
              env:
                - name: MONGO_URI
                  value: "mongodb://samples-logs-db-svc"
                - name: DB_NAME
                  value: "samples_testing"
                - name: PYTHONUNBUFFERED
                  value: "1"

