apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: phylogeny-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            ms: phylogeny-cronjob
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ebi-registry-secret
          containers:
            - name: main
              image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/samples-logs-back-end-cronjob
