apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: phylogeny-cronjob
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            ms: phylogeny-cronjob
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: ebi-registry-secret
          containers:
            - name: main
              image: dockerhub.ebi.ac.uk/c19workflow/covid-workflow-manager/samples-logs-back-end-cronjob
              env:
                - name: MONGO_URI
                  value: "mongodb://samples-logs-db-svc"
                - name: DB_NAME
                  value: "samples"
                - name: PYTHONUNBUFFERED
                  value: "1"

